"LR_CONT": 0.0005
"LR_COMM": 0.0005
"NUM_ENVS": 256
"NUM_STEPS": 40
"TOTAL_TIMESTEPS": 1.e8
"FC_DIM_SIZE": 128
"CRITIC_FC_DIM_SIZE": 256
"COMM_DIM": 32
"ATTENTION_LEN": 4
"ATTENTION_DIM": 64
"GRU_HIDDEN_DIM": 64
"ATTENTION_NUM_HEADS": 4
"UPDATE_EPOCHS": 8
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS_COMM": 0.2
"CLIP_EPS_CONT": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF_CONT": 0.01
"ENT_COEF_COMM": 0.01
"MIN_KL_COEF": 0.0000000
"MAX_KL_COEF": 0.2
"KL_COEF_CONT": 0.00
"KL_COEF_COMM": 0.00
"KL_TARGET_CONT": 0.01
"KL_TARGET_COMM": 0.1
"HF_COEF": 0.0
"VF_COEF": 0.5
"MAX_GRAD_NORM_AC": 0.5
"MAX_GRAD_NORM_CR": 0.5
"ACTIVATION": "relu"
"OBS_WITH_AGENT_ID": True
"SEED": 0
"SAVE_FREQ": 0.1
"NUM_EVAL_TRAJECTORIES": 10
"LOG_INTERVAL": 1
"COMM_INTERVAL": 1
"CONT_INTERVAL": 1
"SIMUL": 0
"ENV_KWARGS":
  "num_agents": 3
  "grid_size": 6
  "max_episode_len": 40
  "comm_type": 'reg'
"ANNEAL_LR": False
"SAVE_PATH": "ingama_coordinate"

# WandB Params
"PROJECT": "InGaMA-Coordinate"
